name: Test

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  test:
    name: Test
    strategy:
      matrix:
        php-version: ['8.4', '8.5']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: composer test
